language: node_js

node_js:
  - node
  - 8.0.0
  - 9.0.0
  - 10.0.0

sudo: false

install:
  - npm install

before_script:
  - npm install -g @vue/cli

after_script: 
  - npm run lint && npm run test && npm run build

notifications:
  email: 
    - synergixe.org@gmail.com
